gerrit:
  ssh:
    user: ${GERRIT_USER}
    hostname: ${GERRIT_HOSTNAME}
    port: ${GERRIT_SSH_PORT}
    key:
      file: ${GERRIT_SSH_KEY_FILE}
      pass: ${GERRIT_SSH_KEY_PASS}

jenkins:
  baseUrl: ${JENKINS_BASE_URL}
  user: ${JENKINS_USER}
  password: ${JENKINS_PASSWORD}
  gerritUser: ${JENKINS_GERRIT_USER}

rest:
  timeout:
    connect: 10000
    read: 60000
