gerrit:
  rest:
    baseUrl: ${GERRIT_BASE_URL}
    user: ${GERRIT_USER}
    password: ${GERRIT_PASSWORD}
    timeout:
      connect:
        ms: 10000
      read:
        ms: 60000
  ssh:
    user: ${GERRIT_USER}
    host: ${GERRIT_HOSTNAME}
    port: ${GERRIT_SSH_PORT}
    key:
      file: ${GERRIT_SSH_KEY_FILE}
      pass: ${GERRIT_SSH_KEY_PASS:}

jenkins:
  rest:
    baseUrl: ${JENKINS_BASE_URL}
    user: ${JENKINS_USER}
    password: ${JENKINS_PASSWORD}
    timeout:
      connect:
        ms: 10000
      read:
        ms: 60000
  gerritUser: ${JENKINS_GERRIT_USER}
